apiVersion: v1
kind: Service
metadata:
  name: camunda-service
  labels:
    app: camunda
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9404'
spec:
  selector:
    app: camunda
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
