camunda.bpm.client:
  base-url: http://127.0.0.1:8080/engine-rest # the URL pointing to the Camunda Platform Runtime REST API
logging.level.org.camunda.bpm.client: DEBUG # increase the log level of the application
