server:
  port: 8081
camunda:
  bpm:
    client:
      lock-duration: 10000 # defines how many milliseconds the External Tasks are locked until they can be fetched again
      subscriptions:
        scoreProvider: # topic name of the External Service Task
          variable-names: [] # our business logic doesn't require any variables, so don't fetch them
          process-definition-key: loan_process # only filter for External Tasks with this process definition key
        loanGranter:
          variable-names: customerId, creditScore # only fetch these two variables
          process-definition-key: loan_process
      max-tasks: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
logging.level.org.camunda.bpm.client: DEBUG # increase the log level of the application
