camunda.bpm.client:
  base-url: http://camunda-service/engine-rest # the URL pointing to the Camunda Platform Runtime REST API
logging.level.org.camunda.bpm.client: DEBUG # increase the log level of the application
