apiVersion: v1
kind: Service
metadata:
  name: poc-external-task-service-local
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: poc-external-task-service-local
subsets:
  - addresses:
      - ip: 192.168.12.7
    ports:
      - port: 80
