apiVersion: v1
kind: Service
metadata:
  name: poc-external-task-service
  labels:
    app: poc-external-task
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '12345'
spec:
  selector:
    app: poc-external-task
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
