apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: poc-external-task-hpa
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poc-external-task-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
